try{
    console.log("A");
    console.log("B");
    console.log("C");
}catch(err){
    console.log("There is an error",err.message);
}finally 
{
    console.log("Finally block is always executed");
}


console.log("hiiiiii")